REDIRECT_URI = "http://localhost:8888/callback"
DEFAULT_LIBRARY_PATH = "./MUSIC LIBRARY"
DEFAULT_LIKES_EXPORT_FILE_NAME = "likes.csv"
DEFAULT_COMPARE_TAGS = "ISRC,ARTIST,TITLE,LENGTH"
DEFAULT_DEST_GROUPING_PATTERN = "%SPOTY_PLAYLIST_NAME%"
DEFAULT_DEST_PRINT_PATTERN = "%SPOTY_PLAYLIST_INDEX%: %SPOTY_TRACK_ID% %ARTIST% - %TITLE%"
