[SPOTIFY]
REDIRECT_URI = "http://localhost:8888/callback"

[DEEZER]
REDIRECT_URI = "http://localhost:8888/callback"

[SPOTY]
DEFAULT_EXPORT_PATH = "./EXPORT"
DEFAULT_LIKES_EXPORT_FILE_NAME = "likes.csv"
DEFAULT_GROUPING_PATTERN = "%SPOTY_PLAYLIST_NAME%"
DEFAULT_PRINT_PATTERN = "%SPOTY_PLAYLIST_INDEX%: %SPOTY_TRACK_ID% %ARTIST% - %TITLE%"
COMPARE_LENGTH_TOLERANCE_SEC = 2
COMPARE_TAGS_DEFINITELY_DUPLICATE = [
    'SPOTY_FILE_NAME',
    'DEEZER_TRACK_ID,SPOTY_LENGTH',
    'SPOTIFY_TRACK_ID,SPOTY_LENGTH',
    'ISRC,SPOTY_LENGTH',
    'ARTIST,TITLE,SPOTY_LENGTH'
]
COMPARE_TAGS_PROBABLY_DUPLICATE = [
    'DEEZER_TRACK_ID',
    'SPOTIFY_TRACK_ID',
    'ISRC',
    'ARTIST,TITLE'
]

[DUPLICATE_PRINT_PATTERNS]
DEEZER = "%ARTIST% - %TITLE% ( Deezer track id: %DEEZER_TRACK_ID% Playlist: %SPOTY_PLAYLIST_NAME%)"
SPOTIFY = "%ARTIST% - %TITLE% ( Spotify track id: %SPOTIFY_TRACK_ID% Playlist: %SPOTY_PLAYLIST_NAME%)"
LOCAL = "%ARTIST% - %TITLE% ( %SPOTY_FILE_NAME% )"
CSV = "%ARTIST% - %TITLE%"